[package]
name = "pacaptr"
description = "A pacman-like wrapper for many package managers."
version = "0.2.0"
authors = ["Rami3L <rami3l@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
subprocess = "0.2.4"
lazy_static = "1.4.0"
# structopt = "0.3"
clap = "3.0.0-beta.1"
colored = "1.9.3"
which = "4.0.0"
# bus_writer = "0.1"
