[package]
name = "pacaptr"
description = "A pacman-like wrapper for many package managers."
version = "0.1.0"
authors = ["Rami3L <rami3l@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
subprocess = "0.2"
lazy_static = "1.4"
structopt = "0.3"
colored = "1.9"
which = "3.1"
# bus_writer = "0.1"
