name: macos-test

on:
  push:
    branches: [master, rs-dev]
  pull_request:
    branches: [master, rs-dev]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run heavy tests
        run: cargo test --verbose -- --ignored
