name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pacaptr
            asset_name: pacaptr-linux-amd64
          - os: windows-latest
            artifact_name: pacaptr.exe
            asset_name: pacaptr-windows-amd64
          - os: macos-latest
            artifact_name: pacaptr
            asset_name: pacaptr-macos-amd64

    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
